### ISSUE TITLE
Irregular card sizes

### ISSUE THREAD

**Issue by ellieyhcheng** [yvonneCh/ResearchUCLA#8]
The cards have different widths on the Research page when the window is contracted enough that there's only one column for cards. 
![image](https://user-images.githubusercontent.com/15387908/56071526-071cd480-5d44-11e9-9e13-9ba7c9db4419.png)
It seems to be due to the title and content lengths of the cards, especially when the content is short.

**Comment by ycyvonne** [comment]
You can handle this by setting a min-width property.
